#!/bin/bash
# requires feh
# Script to automatically change the wallpaper and lockscreen in spectrwm

# Directory containing the wallpapers
DIR="~/Pictures/wall"

while true; do
  # Command to Select wallpapers at random from the $DIR Directory
  WAL=$(ls $DIR/*.{png,jpg} | shuf -n1)

  # Set lockscreen wallpaper
  # cat $WAL > $DIR/current-wallpaper.png
  PIC=$(echo $WAL)

  # Set Desktop wallpaper
  feh --bg-fill $PIC
  # feh --bg-scale $PIC
  sleep 1200 # wait for 20 minutes
done
